BOSS = "PATRON"
SK = "DEPO SORUMLUSU"
ME = "PAZARLAMACI"
WORKER = "SAHA ELEMANI"


PERSONEL_TYPE = (
    (BOSS, "PATRON"),
    (SK, "DEPO SORUMLUSU"),
    (ME, "PAZARLAMACI"),
    (WORKER, "SAHA ELEMANI")
)
