WAITING = "WAITING"
FAIL = "FAIL"
SUCCESS = "SUCCESS"

PRODUCT_ORDER_STATUS = (
    (WAITING, "WAITING"),
    (FAIL, "FAIL"),
    (SUCCESS, "SUCCESS")
)

RAW_ORDER_STATUS = (
    (WAITING, "WAITING"),
    (FAIL, "FAIL"),
    (SUCCESS, "SUCCESS")
)
